name: Sync branches and modifications

on:
  schedule:
    - cron: '0 */4 * * *'  # 每 4 小时执行一次

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: 'target_repo'

    - name: Clone upstream repository
      run: git clone https://github.com/heyong5454/ManifestAutoUpdate.git upstream_repo

    - name: Sync branches and modifications
      run: |
        cd upstream_repo
        # 获取所有分支
        for branch in $(git branch -r | grep -v '\->'); do
          # 去除 "origin/" 前缀
          branch=${branch#origin/}
          # 检查分支是否存在于目标仓库中
          if [ ! `cd ../target_repo && git branch --list $branch` ]; then
            git checkout $branch
            cd ../target_repo
            git checkout -b $branch
            git pull ../upstream_repo $branch
            git push --set-upstream origin $branch
            cd ../upstream_repo
          fi
        done
        # 可以添加额外的脚本来处理分支删除的情况
